### ISSUE TITLE
Google Cloud Platform 上安装一直提示 No such file or directory

### ISSUE THREAD

**Issue by Tanrky** [primovist/snell.sh#2]
cat: /snell-server.conf: No such file or directory

**Comment by primovist** [comment]
请自行运行./snell-server，按提示生成配置文件之后读取配置文件内容。

**Comment by primovist** [comment]
可以试试今天刚刚更新的内容。
centos测试通过，Debian还没测试。

**Comment by Tanrky** [comment]
用新的方案在 VPS 上正常运行了，配置到 Surge 里面不行，后来把端口号改了以后可以正常用了。
